"""baseline schema from models

Revision ID: d1239c0c35eb
Revises:
Create Date: 2026-08-26 22:57:22.003172

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "d1239c0c35eb"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "SKETCH",
                "REDRAWN_SVG",
                "PHOTO",
                "PDF",
                "LOGO",
                name="assetkind",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("content_type", sa.String(length=120), nullable=False),
        sa.Column("storage_path", sa.Text(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("byte_size", sa.BigInteger(), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("storage_path"),
        schema="gd",
    )
    op.create_index(op.f("ix_gd_assets_sha256"), "assets", ["sha256"], unique=False, schema="gd")
    op.create_table(
        "guides",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=160), nullable=False),
        sa.Column("doc_number", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("title_break_after", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
        schema="gd",
    )
    op.create_table(
        "guide_revisions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("guide_id", sa.Integer(), nullable=False),
        sa.Column("rev_label", sa.String(length=32), nullable=False),
        sa.Column("revision_date", sa.Date(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "PUBLISHED",
                "ARCHIVED",
                name="revisionstatus",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("change_note", sa.Text(), nullable=False),
        sa.Column("author_byline", sa.String(length=120), nullable=False),
        sa.Column("approved_by", sa.String(length=120), nullable=True),
        sa.Column("purpose", sa.Text(), nullable=False),
        sa.Column("units", sa.String(length=16), nullable=True),
        sa.Column("scale", sa.String(length=16), nullable=True),
        sa.Column("tolerance", sa.String(length=32), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["guide_id"], ["gd.guides.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("guide_id", "rev_label", name="uq_guide_revisions_guide_rev"),
        schema="gd",
    )
    op.create_index(
        op.f("ix_gd_guide_revisions_guide_id"),
        "guide_revisions",
        ["guide_id"],
        unique=False,
        schema="gd",
    )
    op.create_table(
        "bom_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("revision_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(length=240), nullable=False),
        sa.Column("quantity", sa.String(length=32), nullable=True),
        sa.Column("unit", sa.String(length=32), nullable=True),
        sa.Column("part_number", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(["revision_id"], ["gd.guide_revisions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("revision_id", "position", name="uq_bom_items_revision_position"),
        schema="gd",
    )
    op.create_index(
        op.f("ix_gd_bom_items_revision_id"), "bom_items", ["revision_id"], unique=False, schema="gd"
    )
    op.create_table(
        "renders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("revision_id", sa.Integer(), nullable=False),
        sa.Column("pdf_asset_id", sa.Integer(), nullable=False),
        sa.Column("template_version", sa.String(length=32), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=False),
        sa.Column("rendered_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["pdf_asset_id"], ["gd.assets.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["revision_id"], ["gd.guide_revisions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="gd",
    )
    op.create_index(
        op.f("ix_gd_renders_revision_id"), "renders", ["revision_id"], unique=False, schema="gd"
    )
    op.create_table(
        "required_tools",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("revision_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=240), nullable=False),
        sa.Column("spec", sa.String(length=240), nullable=True),
        sa.ForeignKeyConstraint(["revision_id"], ["gd.guide_revisions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("revision_id", "position", name="uq_required_tools_revision_position"),
        schema="gd",
    )
    op.create_index(
        op.f("ix_gd_required_tools_revision_id"),
        "required_tools",
        ["revision_id"],
        unique=False,
        schema="gd",
    )
    op.create_table(
        "safety_warnings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("revision_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column(
            "severity",
            sa.Enum(
                "DANGER",
                "WARNING",
                "CAUTION",
                "NOTICE",
                name="severity",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("text", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["revision_id"], ["gd.guide_revisions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("revision_id", "position", name="uq_safety_warnings_revision_position"),
        schema="gd",
    )
    op.create_index(
        op.f("ix_gd_safety_warnings_revision_id"),
        "safety_warnings",
        ["revision_id"],
        unique=False,
        schema="gd",
    )
    op.create_table(
        "steps",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("revision_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("instructions", sa.Text(), nullable=False),
        sa.Column("est_minutes", sa.Integer(), nullable=True),
        sa.Column(
            "plate_layout",
            sa.Enum("FULL", "HALF", name="platelayout", native_enum=False, length=8),
            nullable=False,
        ),
        sa.Column("image_asset_id", sa.Integer(), nullable=True),
        sa.Column("side_note", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["image_asset_id"], ["gd.assets.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["revision_id"], ["gd.guide_revisions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("revision_id", "position", name="uq_steps_revision_position"),
        schema="gd",
    )
    op.create_index(
        op.f("ix_gd_steps_revision_id"), "steps", ["revision_id"], unique=False, schema="gd"
    )
    op.create_table(
        "sketch_jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("step_id", sa.Integer(), nullable=False),
        sa.Column("source_asset_id", sa.Integer(), nullable=False),
        sa.Column("result_asset_id", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "SUCCEEDED",
                "FAILED",
                name="sketchjobstatus",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("model", sa.String(length=64), nullable=False),
        sa.Column("prompt_version", sa.String(length=32), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["result_asset_id"], ["gd.assets.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["source_asset_id"], ["gd.assets.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["step_id"], ["gd.steps.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="gd",
    )
    op.create_index(
        op.f("ix_gd_sketch_jobs_status"), "sketch_jobs", ["status"], unique=False, schema="gd"
    )
    op.create_index(
        op.f("ix_gd_sketch_jobs_step_id"), "sketch_jobs", ["step_id"], unique=False, schema="gd"
    )
    op.create_table(
        "step_callouts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("step_id", sa.Integer(), nullable=False),
        sa.Column("index", sa.Integer(), nullable=False),
        sa.Column("x_pct", sa.Float(), nullable=False),
        sa.Column("y_pct", sa.Float(), nullable=False),
        sa.Column(
            "leader_dir",
            sa.Enum("LEFT", "RIGHT", name="leaderdir", native_enum=False, length=8),
            nullable=False,
        ),
        sa.Column("leader_length_pct", sa.Float(), nullable=False),
        sa.Column("label", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["step_id"], ["gd.steps.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("step_id", "index", name="uq_step_callouts_step_index"),
        schema="gd",
    )
    op.create_index(
        op.f("ix_gd_step_callouts_step_id"), "step_callouts", ["step_id"], unique=False, schema="gd"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_gd_step_callouts_step_id"), table_name="step_callouts", schema="gd")
    op.drop_table("step_callouts", schema="gd")
    op.drop_index(op.f("ix_gd_sketch_jobs_step_id"), table_name="sketch_jobs", schema="gd")
    op.drop_index(op.f("ix_gd_sketch_jobs_status"), table_name="sketch_jobs", schema="gd")
    op.drop_table("sketch_jobs", schema="gd")
    op.drop_index(op.f("ix_gd_steps_revision_id"), table_name="steps", schema="gd")
    op.drop_table("steps", schema="gd")
    op.drop_index(
        op.f("ix_gd_safety_warnings_revision_id"), table_name="safety_warnings", schema="gd"
    )
    op.drop_table("safety_warnings", schema="gd")
    op.drop_index(
        op.f("ix_gd_required_tools_revision_id"), table_name="required_tools", schema="gd"
    )
    op.drop_table("required_tools", schema="gd")
    op.drop_index(op.f("ix_gd_renders_revision_id"), table_name="renders", schema="gd")
    op.drop_table("renders", schema="gd")
    op.drop_index(op.f("ix_gd_bom_items_revision_id"), table_name="bom_items", schema="gd")
    op.drop_table("bom_items", schema="gd")
    op.drop_index(op.f("ix_gd_guide_revisions_guide_id"), table_name="guide_revisions", schema="gd")
    op.drop_table("guide_revisions", schema="gd")
    op.drop_table("guides", schema="gd")
    op.drop_index(op.f("ix_gd_assets_sha256"), table_name="assets", schema="gd")
    op.drop_table("assets", schema="gd")
    # ### end Alembic commands ###
