"""ORM models.

Importing this package registers every model on ``Base.metadata``. Alembic's ``env.py``
imports it for exactly that side effect, so a model that is not re-exported here will be
silently missing from autogenerated migrations.
"""

from app.models.asset import Asset, Render, SketchJob
from app.models.blocks import BomItem, RequiredTool, SafetyWarning
from app.models.guide import Guide, GuideRevision
from app.models.step import Step, StepCallout

__all__ = [
    "Asset",
    "BomItem",
    "Guide",
    "GuideRevision",
    "Render",
    "RequiredTool",
    "SafetyWarning",
    "SketchJob",
    "Step",
    "StepCallout",
]
