"""Repository interfaces.

One module holding every ``Protocol``, importing only schemas. Services depend on these,
never on a concrete implementation, so a repository can be swapped or faked without the
service layer noticing.
"""

from __future__ import annotations

from typing import Protocol

from app.schemas.assets import (
    AssetCreateInternal,
    AssetRead,
    RenderCreateInternal,
    RenderRead,
    SketchJobCreateInternal,
    SketchJobPatchInternal,
    SketchJobRead,
)
from app.schemas.blocks import (
    BomItemCreateInternal,
    BomItemPatchInternal,
    BomItemRead,
    RequiredToolCreateInternal,
    RequiredToolPatchInternal,
    RequiredToolRead,
    SafetyWarningCreateInternal,
    SafetyWarningPatchInternal,
    SafetyWarningRead,
)
from app.schemas.enums import SketchJobStatus
from app.schemas.guides import (
    GuideCreateInternal,
    GuidePatchInternal,
    GuideRead,
    RevisionCreateInternal,
    RevisionPatchInternal,
    RevisionRead,
)
from app.schemas.steps import (
    CalloutCreateInternal,
    CalloutPatchInternal,
    CalloutRead,
    StepCreateInternal,
    StepPatchInternal,
    StepRead,
)


class GuideRepository(Protocol):
    """Storage for guide identities."""

    async def create(self, guide: GuideCreateInternal) -> GuideRead: ...
    async def get(self, guide_id: int) -> GuideRead: ...
    async def get_by_slug(self, slug: str) -> GuideRead: ...
    async def list_all(self) -> list[GuideRead]: ...
    async def update(self, guide_id: int, update: GuidePatchInternal) -> GuideRead: ...
    async def delete(self, guide_id: int) -> None: ...


class RevisionRepository(Protocol):
    """Storage for guide revisions."""

    async def create(self, revision: RevisionCreateInternal) -> RevisionRead: ...
    async def get(self, revision_id: int) -> RevisionRead: ...
    async def list_for_guide(self, guide_id: int) -> list[RevisionRead]: ...
    async def update(self, revision_id: int, update: RevisionPatchInternal) -> RevisionRead: ...
    async def delete(self, revision_id: int) -> None: ...


class StepRepository(Protocol):
    """Storage for steps and their callouts."""

    async def create(self, step: StepCreateInternal) -> StepRead: ...
    async def append(self, revision_id: int, step: StepCreateInternal) -> StepRead: ...
    async def get(self, step_id: int) -> StepRead: ...
    async def list_for_revision(self, revision_id: int) -> list[StepRead]: ...
    async def update(self, step_id: int, update: StepPatchInternal) -> StepRead: ...
    async def delete(self, step_id: int) -> None: ...
    async def reorder(self, revision_id: int, order: dict[int, int]) -> list[StepRead]: ...

    async def add_callout(self, callout: CalloutCreateInternal) -> CalloutRead: ...
    async def get_callout(self, callout_id: int) -> CalloutRead: ...
    async def update_callout(
        self, callout_id: int, update: CalloutPatchInternal
    ) -> CalloutRead: ...
    async def delete_callout(self, callout_id: int) -> None: ...
    async def clear_callouts(self, step_id: int) -> None: ...


class BomItemRepository(Protocol):
    """Storage for bill-of-materials lines."""

    async def append(self, revision_id: int, item: BomItemCreateInternal) -> BomItemRead: ...
    async def get(self, item_id: int) -> BomItemRead: ...
    async def list_for_revision(self, revision_id: int) -> list[BomItemRead]: ...
    async def update(self, item_id: int, update: BomItemPatchInternal) -> BomItemRead: ...
    async def delete(self, item_id: int) -> None: ...
    async def reorder(self, revision_id: int, order: dict[int, int]) -> list[BomItemRead]: ...


class RequiredToolRepository(Protocol):
    """Storage for required-tool lines."""

    async def append(
        self, revision_id: int, item: RequiredToolCreateInternal
    ) -> RequiredToolRead: ...
    async def get(self, item_id: int) -> RequiredToolRead: ...
    async def list_for_revision(self, revision_id: int) -> list[RequiredToolRead]: ...
    async def update(self, item_id: int, update: RequiredToolPatchInternal) -> RequiredToolRead: ...
    async def delete(self, item_id: int) -> None: ...
    async def reorder(self, revision_id: int, order: dict[int, int]) -> list[RequiredToolRead]: ...


class SafetyWarningRepository(Protocol):
    """Storage for safety warnings."""

    async def append(
        self, revision_id: int, item: SafetyWarningCreateInternal
    ) -> SafetyWarningRead: ...
    async def get(self, item_id: int) -> SafetyWarningRead: ...
    async def list_for_revision(self, revision_id: int) -> list[SafetyWarningRead]: ...
    async def update(
        self, item_id: int, update: SafetyWarningPatchInternal
    ) -> SafetyWarningRead: ...
    async def delete(self, item_id: int) -> None: ...
    async def reorder(self, revision_id: int, order: dict[int, int]) -> list[SafetyWarningRead]: ...


class AssetRepository(Protocol):
    """Storage for stored-file metadata."""

    async def create(self, asset: AssetCreateInternal) -> AssetRead: ...
    async def get(self, asset_id: int) -> AssetRead: ...
    async def find_by_sha256(self, sha256: str) -> AssetRead | None: ...


class SketchJobRepository(Protocol):
    """Storage for sketch-redraw jobs."""

    async def create(self, job: SketchJobCreateInternal) -> SketchJobRead: ...
    async def get(self, job_id: int) -> SketchJobRead: ...
    async def list_for_step(self, step_id: int) -> list[SketchJobRead]: ...
    async def list_by_status(self, status: SketchJobStatus) -> list[SketchJobRead]: ...
    async def update(self, job_id: int, update: SketchJobPatchInternal) -> SketchJobRead: ...


class RenderRepository(Protocol):
    """Storage for produced PDFs."""

    async def create(self, render: RenderCreateInternal) -> RenderRead: ...
    async def get(self, render_id: int) -> RenderRead: ...
    async def list_for_revision(self, revision_id: int) -> list[RenderRead]: ...
    async def latest_for_revision(self, revision_id: int) -> RenderRead | None: ...
